/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.minimundo.Presentation.Desktop;

/**
 *
 * @author denil
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mmuFornecedores = new javax.swing.JMenuItem();
        mmuProdutos = new javax.swing.JMenuItem();
        mmuUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mmuCompra = new javax.swing.JMenuItem();
        mmuVenda = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Mundo System");

        jMenu1.setText("Cadastros");

        mmuFornecedores.setText("Fornecedores");
        mmuFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmuFornecedoresMouseClicked(evt);
            }
        });
        mmuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmuFornecedoresActionPerformed(evt);
            }
        });
        jMenu1.add(mmuFornecedores);

        mmuProdutos.setText("Produtos");
        mmuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(mmuProdutos);

        mmuUsuarios.setText("Usuários");
        mmuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(mmuUsuarios);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Serviços");

        mmuCompra.setText("Compra");
        jMenu3.add(mmuCompra);

        mmuVenda.setText("Venda");
        jMenu3.add(mmuVenda);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Consultas");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mmuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmuFornecedoresActionPerformed
        TelaEditarFornecedores tela = new TelaEditarFornecedores();
        this.add(tela);
        tela.show();
    }//GEN-LAST:event_mmuFornecedoresActionPerformed

    private void mmuFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmuFornecedoresMouseClicked

    }//GEN-LAST:event_mmuFornecedoresMouseClicked

    private void mmuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmuProdutosActionPerformed
        TelaEditarProdutos tela = new TelaEditarProdutos();
        this.add(tela);
        tela.show();
    }//GEN-LAST:event_mmuProdutosActionPerformed

    private void mmuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmuUsuariosActionPerformed
        TelaEditarUsuarios tela = new TelaEditarUsuarios();
        this.add(tela);
        tela.show();
    }//GEN-LAST:event_mmuUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mmuCompra;
    private javax.swing.JMenuItem mmuFornecedores;
    private javax.swing.JMenuItem mmuProdutos;
    private javax.swing.JMenuItem mmuUsuarios;
    private javax.swing.JMenuItem mmuVenda;
    // End of variables declaration//GEN-END:variables
}
